//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSAKWrapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSAKWrapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add active geocache.
        /// </summary>
        internal static string AddActiveGeocache {
            get {
                return ResourceManager.GetString("AddActiveGeocache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add child waypoints.
        /// </summary>
        internal static string AddChildWaypoints {
            get {
                return ResourceManager.GetString("AddChildWaypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add flow.
        /// </summary>
        internal static string AddFlow {
            get {
                return ResourceManager.GetString("AddFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to geocache collection.
        /// </summary>
        internal static string AddToGeocacheCollection {
            get {
                return ResourceManager.GetString("AddToGeocacheCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to ignore list.
        /// </summary>
        internal static string AddToIgnoreList {
            get {
                return ResourceManager.GetString("AddToIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User Flagged geocaches.
        /// </summary>
        internal static string AddUserFlaggedGeocaches {
            get {
                return ResourceManager.GetString("AddUserFlaggedGeocaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        internal static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Waypoint.
        /// </summary>
        internal static string AsWaypoint {
            get {
                return ResourceManager.GetString("AsWaypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Bad parameter value.
        /// </summary>
        internal static string BadParameterValue {
            get {
                return ResourceManager.GetString("BadParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed date.
        /// </summary>
        internal static string ChangedDate {
            get {
                return ResourceManager.GetString("ChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChildLoad.
        /// </summary>
        internal static string ChildLoad {
            get {
                return ResourceManager.GetString("ChildLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Waypoint by user.
        /// </summary>
        internal static string ChildWaypointByUser {
            get {
                return ResourceManager.GetString("ChildWaypointByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Waypoint code.
        /// </summary>
        internal static string ChildWaypointCode {
            get {
                return ResourceManager.GetString("ChildWaypointCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Waypoint comment.
        /// </summary>
        internal static string ChildWaypointComment {
            get {
                return ResourceManager.GetString("ChildWaypointComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Waypoint date.
        /// </summary>
        internal static string ChildWaypointDate {
            get {
                return ResourceManager.GetString("ChildWaypointDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child distance from location (km).
        /// </summary>
        internal static string ChildWaypointDistanceFromLocationKm {
            get {
                return ResourceManager.GetString("ChildWaypointDistanceFromLocationKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Waypoint flag.
        /// </summary>
        internal static string ChildWaypointFlag {
            get {
                return ResourceManager.GetString("ChildWaypointFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Waypoint latitude.
        /// </summary>
        internal static string ChildWaypointLatitude {
            get {
                return ResourceManager.GetString("ChildWaypointLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Waypoint longitude.
        /// </summary>
        internal static string ChildWaypointLongitude {
            get {
                return ResourceManager.GetString("ChildWaypointLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Waypoint name.
        /// </summary>
        internal static string ChildWaypointName {
            get {
                return ResourceManager.GetString("ChildWaypointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Waypoint prefix.
        /// </summary>
        internal static string ChildWaypointPrefix {
            get {
                return ResourceManager.GetString("ChildWaypointPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Waypoints.
        /// </summary>
        internal static string ChildWaypoints {
            get {
                return ResourceManager.GetString("ChildWaypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Waypoint type.
        /// </summary>
        internal static string ChildWaypointType {
            get {
                return ResourceManager.GetString("ChildWaypointType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear macro flag.
        /// </summary>
        internal static string ClearMacroFlag {
            get {
                return ResourceManager.GetString("ClearMacroFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear user flag.
        /// </summary>
        internal static string ClearUserFlag {
            get {
                return ResourceManager.GetString("ClearUserFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        internal static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare to.
        /// </summary>
        internal static string CompareTo {
            get {
                return ResourceManager.GetString("CompareTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare two dates.
        /// </summary>
        internal static string CompareTwoDates {
            get {
                return ResourceManager.GetString("CompareTwoDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        internal static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution context functions.
        /// </summary>
        internal static string ContextGroup {
            get {
                return ResourceManager.GetString("ContextGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate Functions.
        /// </summary>
        internal static string CoordinateFunctions {
            get {
                return ResourceManager.GetString("CoordinateFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to database.
        /// </summary>
        internal static string CopyToDatabase {
            get {
                return ResourceManager.GetString("CopyToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        internal static string County {
            get {
                return ResourceManager.GetString("County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date.
        /// </summary>
        internal static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating file....
        /// </summary>
        internal static string CreatingFile {
            get {
                return ResourceManager.GetString("CreatingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom date field.
        /// </summary>
        internal static string CustomDate {
            get {
                return ResourceManager.GetString("CustomDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom numeric field.
        /// </summary>
        internal static string CustomNumber {
            get {
                return ResourceManager.GetString("CustomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom text field.
        /// </summary>
        internal static string CustomText {
            get {
                return ResourceManager.GetString("CustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        internal static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete flow {0}?.
        /// </summary>
        internal static string Delete_flow_ {
            get {
                return ResourceManager.GetString("Delete_flow_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from database.
        /// </summary>
        internal static string DeleteFromDatabase {
            get {
                return ResourceManager.GetString("DeleteFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigonometric function Inverse Cosine.
        /// </summary>
        internal static string DescrACos {
            get {
                return ResourceManager.GetString("DescrACos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position of the first character in the alphabet.
        /// </summary>
        internal static string DescrAlphaPos {
            get {
                return ResourceManager.GetString("DescrAlphaPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of the positions of all characters in the alphabet.
        /// </summary>
        internal static string DescrAlphaSum {
            get {
                return ResourceManager.GetString("DescrAlphaSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigonometric function Inverse Sine.
        /// </summary>
        internal static string DescrASin {
            get {
                return ResourceManager.GetString("DescrASin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigonometric function Inverse Tangent.
        /// </summary>
        internal static string DescrATan {
            get {
                return ResourceManager.GetString("DescrATan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives the bearing from coord1 to coord2
        ///Bearing(coord1; coord2).
        /// </summary>
        internal static string DescrBearing {
            get {
                return ResourceManager.GetString("DescrBearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set options of execution context.
        ///SetContext(&quot;Rad&quot;).
        /// </summary>
        internal static string DescrContext {
            get {
                return ResourceManager.GetString("DescrContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigonometric function Cosine.
        /// </summary>
        internal static string DescrCos {
            get {
                return ResourceManager.GetString("DescrCos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigonometric function Hyperbolic Cosine.
        /// </summary>
        internal static string DescrCosH {
            get {
                return ResourceManager.GetString("DescrCosH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossbearing between 2 points and 2 directions
        ///Crossbearing(coord1; angle1; coord2; angle2).
        /// </summary>
        internal static string DescrCrossBearing {
            get {
                return ResourceManager.GetString("DescrCrossBearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product of all single numbers in the number.
        ///Example: CP(1234) = 24.
        /// </summary>
        internal static string DescrCrossProduct {
            get {
                return ResourceManager.GetString("DescrCrossProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of all single numbers in the parameter.
        ///Example: CT(654321) = 21.
        /// </summary>
        internal static string DescrCrossTotal {
            get {
                return ResourceManager.GetString("DescrCrossTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives the distance between coord1 and coord2 in meters
        ///Distance(coord1; coord2).
        /// </summary>
        internal static string DescrDistance {
            get {
                return ResourceManager.GetString("DescrDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute the factorial of an integer.
        ///Fact(10) = 3628800.
        /// </summary>
        internal static string DescrFactorial {
            get {
                return ResourceManager.GetString("DescrFactorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterated Crossproduct until result has only 1 digit.
        ///Example: ICP(1234) = 8.
        /// </summary>
        internal static string DescrICrossProduct {
            get {
                return ResourceManager.GetString("DescrICrossProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterated Crosstotal until result has only 1 digit.
        ///Example: ICT(123456) = 3.
        /// </summary>
        internal static string DescrICrossTotal {
            get {
                return ResourceManager.GetString("DescrICrossTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives the number before the decimal point
        ///Int(-5.8) = -5.
        /// </summary>
        internal static string DescrInt {
            get {
                return ResourceManager.GetString("DescrInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersection of 2 Lines (coord1-coord2) with (coord3-coord4).
        ///Intersection(coord1; coord2; coord3; coord4).
        /// </summary>
        internal static string DescrIntersection {
            get {
                return ResourceManager.GetString("DescrIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the latitude from a coordinate as decimal number.
        ///Latitude(&quot;N 51° 12.081 E 6° 50.328&quot;) = 51.20135.
        /// </summary>
        internal static string DescrLatitude {
            get {
                return ResourceManager.GetString("DescrLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers of characters in the string.
        /// </summary>
        internal static string DescrLen {
            get {
                return ResourceManager.GetString("DescrLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the latitude from a coordinate as decimal number.
        ///Longitude(&quot;N 51° 12.081 E 6° 50.328&quot;) = 6.8388.
        /// </summary>
        internal static string DescrLongitude {
            get {
                return ResourceManager.GetString("DescrLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return a substring of a string. Parameter 3: Default=1
        ///Mid(\&quot;String\&quot;;StartPosition;[CharacterCount]).
        /// </summary>
        internal static string DescrMid {
            get {
                return ResourceManager.GetString("DescrMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cache selected. (Quicknotes).
        /// </summary>
        internal static string DescrNoCacheSelected {
            get {
                return ResourceManager.GetString("DescrNoCacheSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position of the first character on the phone keyboard.
        /// </summary>
        internal static string DescrPhoneCode {
            get {
                return ResourceManager.GetString("DescrPhoneCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of the positions of all characters on the phone keyboard.
        /// </summary>
        internal static string DescrPhoneSum {
            get {
                return ResourceManager.GetString("DescrPhoneSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives the number Pi with n digits after decimal point
        ///Pi(4) = 3.1415.
        /// </summary>
        internal static string DescrPi {
            get {
                return ResourceManager.GetString("DescrPi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute the power of the first to the second parameter
        ///Pow(2;10) = 1024.
        /// </summary>
        internal static string DescrPow {
            get {
                return ResourceManager.GetString("DescrPow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimeIndex(y) Gives the index of the prime number y.
        ///Example: PrimeIndex(11) = 5.
        /// </summary>
        internal static string DescrPrimeIndex {
            get {
                return ResourceManager.GetString("DescrPrimeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primenumber(x) Gives the x-th prime number.
        ///Example: Primenumber(5) = 11.
        /// </summary>
        internal static string DescrPrimeNumber {
            get {
                return ResourceManager.GetString("DescrPrimeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection of Coordinate.
        ///Projection(coord; length; angle).
        /// </summary>
        internal static string DescrProjection {
            get {
                return ResourceManager.GetString("DescrProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverses the string
        ///Reverse(&quot;ABC&quot;) = CBA.
        /// </summary>
        internal static string DescrReverse {
            get {
                return ResourceManager.GetString("DescrReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roman numerals to decimal.
        /// </summary>
        internal static string DescrRom2Dec {
            get {
                return ResourceManager.GetString("DescrRom2Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives the Rot13 encryption
        ///Rot13(&quot;ABC&quot;) = NOP.
        /// </summary>
        internal static string DescrRot13 {
            get {
                return ResourceManager.GetString("DescrRot13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds the number to x digits
        ///Round(1.8672; 2) = 1.87.
        /// </summary>
        internal static string DescrRound {
            get {
                return ResourceManager.GetString("DescrRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigonometric function Sine.
        /// </summary>
        internal static string DescrSin {
            get {
                return ResourceManager.GetString("DescrSin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigonometric function Hyperbolic Sine.
        /// </summary>
        internal static string DescrSinH {
            get {
                return ResourceManager.GetString("DescrSinH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigonometric function Tangent.
        /// </summary>
        internal static string DescrTan {
            get {
                return ResourceManager.GetString("DescrTan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigonometric function Hyperbolic Tangent.
        /// </summary>
        internal static string DescrTanH {
            get {
                return ResourceManager.GetString("DescrTanH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get coordinates of a geocache waypoint by its name.
        ///Waypoint(&quot;FN2Y73E&quot;) = &quot;N 51° 12.345 E 006° 43.210&quot;
        ///No param gives cache coordinates..
        /// </summary>
        internal static string DescrWaypoint {
            get {
                return ResourceManager.GetString("DescrWaypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNF (Did Not Find).
        /// </summary>
        internal static string DidNotFind {
            get {
                return ResourceManager.GetString("DidNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNF Date.
        /// </summary>
        internal static string DidNotFindDate {
            get {
                return ResourceManager.GetString("DidNotFindDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from center (km).
        /// </summary>
        internal static string DistanceFromCenterKm {
            get {
                return ResourceManager.GetString("DistanceFromCenterKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from location (km).
        /// </summary>
        internal static string DistanceFromLocationKm {
            get {
                return ResourceManager.GetString("DistanceFromLocationKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division by zero.
        /// </summary>
        internal static string DivByZero {
            get {
                return ResourceManager.GetString("DivByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands.
        /// </summary>
        internal static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit flow sequences.
        /// </summary>
        internal static string EditFlowSequences {
            get {
                return ResourceManager.GetString("EditFlowSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation.
        /// </summary>
        internal static string Elevation {
            get {
                return ResourceManager.GetString("Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all geocaches.
        /// </summary>
        internal static string EmptyDatabase {
            get {
                return ResourceManager.GetString("EmptyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute once.
        /// </summary>
        internal static string ExecuteOnce {
            get {
                return ResourceManager.GetString("ExecuteOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export active flow.
        /// </summary>
        internal static string ExportActiveFlow {
            get {
                return ResourceManager.GetString("ExportActiveFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all flows.
        /// </summary>
        internal static string ExportAllFlows {
            get {
                return ResourceManager.GetString("ExportAllFlows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel.
        /// </summary>
        internal static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export GGZ.
        /// </summary>
        internal static string ExportGGZ {
            get {
                return ResourceManager.GetString("ExportGGZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export GPX.
        /// </summary>
        internal static string ExportGPX {
            get {
                return ResourceManager.GetString("ExportGPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting GPX....
        /// </summary>
        internal static string ExportingGPX {
            get {
                return ResourceManager.GetString("ExportingGPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        internal static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite points.
        /// </summary>
        internal static string FavPoints {
            get {
                return ResourceManager.GetString("FavPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished flow.
        /// </summary>
        internal static string FinishedFlow {
            get {
                return ResourceManager.GetString("FinishedFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing action.
        /// </summary>
        internal static string FinishingAction {
            get {
                return ResourceManager.GetString("FinishingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database to execute the flow on.
        ///Leave empty to use the default database of the sequence..
        /// </summary>
        internal static string FlowDatabaseWithinSequence {
            get {
                return ResourceManager.GetString("FlowDatabaseWithinSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow {0} finished in {1} seconds.
        /// </summary>
        internal static string FlowFinishedIn {
            get {
                return ResourceManager.GetString("FlowFinishedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow name.
        /// </summary>
        internal static string FlowName {
            get {
                return ResourceManager.GetString("FlowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flows.
        /// </summary>
        internal static string Flows {
            get {
                return ResourceManager.GetString("Flows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow sequence {0} finished in {1} seconds.
        /// </summary>
        internal static string FlowSequenceFinishedIn {
            get {
                return ResourceManager.GetString("FlowSequenceFinishedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow sequences.
        /// </summary>
        internal static string FlowSequences {
            get {
                return ResourceManager.GetString("FlowSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula solver.
        /// </summary>
        internal static string FormulaSolver {
            get {
                return ResourceManager.GetString("FormulaSolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula Solver Help.
        /// </summary>
        internal static string FormulaSolverHelp {
            get {
                return ResourceManager.GetString("FormulaSolverHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        internal static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found by me date.
        /// </summary>
        internal static string FoundByMeDate {
            get {
                return ResourceManager.GetString("FoundByMeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found count.
        /// </summary>
        internal static string FoundCount {
            get {
                return ResourceManager.GetString("FoundCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTF (First To Find).
        /// </summary>
        internal static string FTF {
            get {
                return ResourceManager.GetString("FTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        internal static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GC note.
        /// </summary>
        internal static string GCNote {
            get {
                return ResourceManager.GetString("GCNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocache.
        /// </summary>
        internal static string Geocache {
            get {
                return ResourceManager.GetString("Geocache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocache code.
        /// </summary>
        internal static string GeocacheCode {
            get {
                return ResourceManager.GetString("GeocacheCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocache collections.
        /// </summary>
        internal static string GeocacheCollections {
            get {
                return ResourceManager.GetString("GeocacheCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocache container.
        /// </summary>
        internal static string GeocacheContainer {
            get {
                return ResourceManager.GetString("GeocacheContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocache counter.
        /// </summary>
        internal static string GeocacheCountLimit {
            get {
                return ResourceManager.GetString("GeocacheCountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocache name.
        /// </summary>
        internal static string GeocacheName {
            get {
                return ResourceManager.GetString("GeocacheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocache type.
        /// </summary>
        internal static string GeocacheType {
            get {
                return ResourceManager.GetString("GeocacheType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPX settings.
        /// </summary>
        internal static string GPXSettings {
            get {
                return ResourceManager.GetString("GPXSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has corrected.
        /// </summary>
        internal static string HasCorrected {
            get {
                return ResourceManager.GetString("HasCorrected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has travel bug (TB/Coin).
        /// </summary>
        internal static string HasTravelBug {
            get {
                return ResourceManager.GetString("HasTravelBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has user note.
        /// </summary>
        internal static string HasUserNote {
            get {
                return ResourceManager.GetString("HasUserNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import flows.
        /// </summary>
        internal static string ImportFlows {
            get {
                return ResourceManager.GetString("ImportFlows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In ignore list of other database.
        /// </summary>
        internal static string InIgnoreListOfDatabase {
            get {
                return ResourceManager.GetString("InIgnoreListOfDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert formula.
        /// </summary>
        internal static string InsertFormula {
            get {
                return ResourceManager.GetString("InsertFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert waypoint.
        /// </summary>
        internal static string InsertWaypoint {
            get {
                return ResourceManager.GetString("InsertWaypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install default GSAK Wrapper macro.
        /// </summary>
        internal static string InstallDefaultGSAKWrapperMacro {
            get {
                return ResourceManager.GetString("InstallDefaultGSAKWrapperMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install macro for add to collection.
        /// </summary>
        internal static string InstallMacroForAddToCollection {
            get {
                return ResourceManager.GetString("InstallMacroForAddToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install macro for formula solver.
        /// </summary>
        internal static string InstallMacroForFormulaSolver {
            get {
                return ResourceManager.GetString("InstallMacroForFormulaSolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install GSAK macro for this flow.
        /// </summary>
        internal static string InstallMacroForThisFlow {
            get {
                return ResourceManager.GetString("InstallMacroForThisFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install GSAK macro for this sequence.
        /// </summary>
        internal static string InstallMacroForThisSequence {
            get {
                return ResourceManager.GetString("InstallMacroForThisSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is owner.
        /// </summary>
        internal static string IsOwner {
            get {
                return ResourceManager.GetString("IsOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPremium (PMO).
        /// </summary>
        internal static string IsPremium {
            get {
                return ResourceManager.GetString("IsPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last found date.
        /// </summary>
        internal static string LastFoundDate {
            get {
                return ResourceManager.GetString("LastFoundDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last GPX date.
        /// </summary>
        internal static string LastGPXDate {
            get {
                return ResourceManager.GetString("LastGPXDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last log date.
        /// </summary>
        internal static string LastLogDate {
            get {
                return ResourceManager.GetString("LastLogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last user date.
        /// </summary>
        internal static string LastUserDate {
            get {
                return ResourceManager.GetString("LastUserDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default database to execute flows on.
        ///Leave empty to use the active database..
        /// </summary>
        internal static string LeaveEmptyForActiveDatabase {
            get {
                return ResourceManager.GetString("LeaveEmptyForActiveDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged by user.
        /// </summary>
        internal static string LogByUser {
            get {
                return ResourceManager.GetString("LogByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log date.
        /// </summary>
        internal static string LogDate {
            get {
                return ResourceManager.GetString("LogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log date by user.
        /// </summary>
        internal static string LogDateByUser {
            get {
                return ResourceManager.GetString("LogDateByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log encoded.
        /// </summary>
        internal static string LogEncoded {
            get {
                return ResourceManager.GetString("LogEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log text.
        /// </summary>
        internal static string LogText {
            get {
                return ResourceManager.GetString("LogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log type.
        /// </summary>
        internal static string LogType {
            get {
                return ResourceManager.GetString("LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log type by user.
        /// </summary>
        internal static string LogTypeByUser {
            get {
                return ResourceManager.GetString("LogTypeByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Htm.
        /// </summary>
        internal static string LongHtm {
            get {
                return ResourceManager.GetString("LongHtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro.
        /// </summary>
        internal static string Macro {
            get {
                return ResourceManager.GetString("Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MacroFlag.
        /// </summary>
        internal static string MacroFlag {
            get {
                return ResourceManager.GetString("MacroFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSAK Wrapper.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Argument missing. (Min. {1}).
        /// </summary>
        internal static string MissingArgument {
            get {
                return ResourceManager.GetString("MissingArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert declarations for the missing variables:
        ///{0}.
        /// </summary>
        internal static string MissingVariables {
            get {
                return ResourceManager.GetString("MissingVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocache name.
        /// </summary>
        internal static string NameContains {
            get {
                return ResourceManager.GetString("NameContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New flow sequence.
        /// </summary>
        internal static string NewFlowSequence {
            get {
                return ResourceManager.GetString("NewFlowSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No crossing.
        /// </summary>
        internal static string NoCrossing {
            get {
                return ResourceManager.GetString("NoCrossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No proper coordinate string selected.
        ///Please select a complete coordinate string and try again..
        /// </summary>
        internal static string NoProperCoordSelected {
            get {
                return ResourceManager.GetString("NoProperCoordSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Functions.
        /// </summary>
        internal static string NumberFunctions {
            get {
                return ResourceManager.GetString("NumberFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of logs.
        /// </summary>
        internal static string NumberOfLogs {
            get {
                return ResourceManager.GetString("NumberOfLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original text.
        /// </summary>
        internal static string OriginalText {
            get {
                return ResourceManager.GetString("OriginalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Names.
        /// </summary>
        internal static string OtherNames {
            get {
                return ResourceManager.GetString("OtherNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite flow {0}?.
        /// </summary>
        internal static string Overwrite_flow_ {
            get {
                return ResourceManager.GetString("Overwrite_flow_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing data.
        /// </summary>
        internal static string OverwriteExistingData {
            get {
                return ResourceManager.GetString("OverwriteExistingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner name.
        /// </summary>
        internal static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi: Maximum digits: 1000.
        /// </summary>
        internal static string PiMaxDigits {
            get {
                return ResourceManager.GetString("PiMaxDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi: Argument out of range: (0 - 1000).
        /// </summary>
        internal static string PiMinDigits {
            get {
                return ResourceManager.GetString("PiMinDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed by.
        /// </summary>
        internal static string PlacedBy {
            get {
                return ResourceManager.GetString("PlacedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed date.
        /// </summary>
        internal static string PlacedDate {
            get {
                return ResourceManager.GetString("PlacedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing action.
        /// </summary>
        internal static string PreparingAction {
            get {
                return ResourceManager.GetString("PreparingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present in collection.
        /// </summary>
        internal static string PresentInCollection {
            get {
                return ResourceManager.GetString("PresentInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present in other database.
        /// </summary>
        internal static string PresentInOtherDatabase {
            get {
                return ResourceManager.GetString("PresentInOtherDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running action.
        /// </summary>
        internal static string RunningAction {
            get {
                return ResourceManager.GetString("RunningAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select root data folder.
        /// </summary>
        internal static string SelectRootDataFolder {
            get {
                return ResourceManager.GetString("SelectRootDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Waypoint.
        /// </summary>
        internal static string SelectWaypoint {
            get {
                return ResourceManager.GetString("SelectWaypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set macro flag.
        /// </summary>
        internal static string SetMacroFlag {
            get {
                return ResourceManager.GetString("SetMacroFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user flag.
        /// </summary>
        internal static string SetUserFlag {
            get {
                return ResourceManager.GetString("SetUserFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Htm.
        /// </summary>
        internal static string ShortHtm {
            get {
                return ResourceManager.GetString("ShortHtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart name.
        /// </summary>
        internal static string SmartNameContains {
            get {
                return ResourceManager.GetString("SmartNameContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart override.
        /// </summary>
        internal static string SmartOverride {
            get {
                return ResourceManager.GetString("SmartOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve.
        /// </summary>
        internal static string Solve {
            get {
                return ResourceManager.GetString("Solve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting flow.
        /// </summary>
        internal static string StartingFlow {
            get {
                return ResourceManager.GetString("StartingFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporarily disabled.
        /// </summary>
        internal static string TempDisabled {
            get {
                return ResourceManager.GetString("TempDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        internal static string Terrain {
            get {
                return ResourceManager.GetString("Terrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Functions.
        /// </summary>
        internal static string TextFunctions {
            get {
                return ResourceManager.GetString("TextFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: To much arguments. (Max. {1}).
        /// </summary>
        internal static string TooManyArguments {
            get {
                return ResourceManager.GetString("TooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigonometric functions.
        /// </summary>
        internal static string TrigGroup {
            get {
                return ResourceManager.GetString("TrigGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown function:.
        /// </summary>
        internal static string UnknownFunction {
            get {
                return ResourceManager.GetString("UnknownFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Function Group.
        /// </summary>
        internal static string UnknownFunctionGroup {
            get {
                return ResourceManager.GetString("UnknownFunctionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data numeric.
        /// </summary>
        internal static string UserDataNumber {
            get {
                return ResourceManager.GetString("UserDataNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data text.
        /// </summary>
        internal static string UserDataText {
            get {
                return ResourceManager.GetString("UserDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User flag.
        /// </summary>
        internal static string UserFlag {
            get {
                return ResourceManager.GetString("UserFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User flag set in other database.
        /// </summary>
        internal static string UserFlagInOtherDatabase {
            get {
                return ResourceManager.GetString("UserFlagInOtherDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User note date.
        /// </summary>
        internal static string UserNoteDate {
            get {
                return ResourceManager.GetString("UserNoteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Value out of range. ({1} - {2}).
        /// </summary>
        internal static string ValueOutOfRange {
            get {
                return ResourceManager.GetString("ValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        internal static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoint.
        /// </summary>
        internal static string Waypoint {
            get {
                return ResourceManager.GetString("Waypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoints.
        /// </summary>
        internal static string Waypoints {
            get {
                return ResourceManager.GetString("Waypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where.
        /// </summary>
        internal static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        internal static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
    }
}
